### ISSUE TITLE
fails with python 3.4

### ISSUE THREAD

**Issue by vetinari** [zalando-incubator/zalando-deploy-cli#59]
```
Writing NOTES.txt.. EXCEPTION OCCURRED: mkdir() got an unexpected keyword argument 'exist_ok'
Traceback (most recent call last):
  File "/usr/local/bin/zdeploy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/zalando_deploy_cli/cli.py", line 760, in main
    cli()
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/zalando_deploy_cli/cli.py", line 750, in init
    copy_template(template_path, path, variables)
  File "/usr/local/lib/python3.4/dist-packages/zalando_deploy_cli/cli.py", line 649, in copy_template
    target_path.parent.mkdir(parents=True, exist_ok=True)
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'
```

**Comment by vetinari** [comment]
see also https://github.com/zalando-incubator/zalando-deploy-cli/pull/54
